In [1]:
import numpy as np


In [3]:
# VECTOR
v=np.array([1,2,3,4,5])
v


array([1, 2, 3, 4, 5])

In [4]:
# MATRIX
m=np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# SPECIAL ARRAY
z=np.zeros((2,3))     # all 0
o=np.ones((2,2))      # all 1
e=np.eye(3)           # identity matrix
ar=np.arange(0, 10, 2) # [0,2,4,6,8]
lin=np.linspace(0, 1, 5) # 5 numbers between 0 and 1

print(z,o,e,ar,lin,sep="\n")

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [14]:
# PROPERTIES
a=np.array([[5,4,3,2,4,2],[2,3,2,3,4,3],[2,2,3,2,3,2]])
print('shape= ',a.shape)    # dimensions (rows, cols)
print('dim= ',a.ndim)     # number of dimensions
print('size= ',a.size)     # total elements
print('dtype= ',a.dtype)    # data type

shape=  (3, 6)
dim=  2
size=  18
dtype=  int64


In [23]:
# INDEXING
a=np.array([2,2,3,2,3,2])
print(a[0])   
print(a[a!=3])        

2
[2 2 2 2]


In [ ]:
# SLICING
a=np.arange(1,31).reshape(6,5)
print(a)
print(a[0:2,1:2])  #perticular sub matrix
print(a[:,2].reshape(6,1))   #column
print(a[2,:])  #row


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [25]:
# RESHAPE
a = np.arange(6)

a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [26]:
#  OPERATION
a = np.array([1,2,3])
b = np.array([4,5,6])

a + b     # [5,7,9]
a * b     # [4,10,18]
a ** 2    # [1,4,9]

array([1, 4, 9])

In [ ]:
#  STATISTICS
print(np.sum(a))
print(np.mean(a))
print(np.min(a))
print(np.max(a))
print(np.std(a))

6
2.0
1
3
0.816496580927726


In [ ]:
#  BROADCASTING 
a = np.array([1,2,3])
b = 2

a + b   # [3,4,5]   WHEN operation [1,2,3] + [2,2,2] (THIS IS BROADCASTING )
a / b
a // b
a * b
a ** b

In [28]:
# ITERATION 
for x in a:
    print(x)

1
2
3


In [29]:
#  LINEAR ALGEBRA 
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(np.dot(a, b)      )  # matrix multiplication
print(np.linalg.inv(a)   ) # inverse
print(np.linalg.det(a)    )# determinant

[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004


In [30]:
# SAVE AND LOAD
np.save('file.npy', a)


In [31]:
np.load('file.npy')

array([[1, 2],
       [3, 4]])

In [ ]:

#  CRUD
arr = np.array([1,2,3,4,5])

# CREATE
arr = np.append(arr, 6)

# READ
print(arr[arr % 2 == 0])

# UPDATE
arr[arr > 3] = 0

# DELETE
arr = np.delete(arr, 1)

[2 4 6]


In [34]:

# =========================
# CREATE MATRICES
# =========================
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

# =========================
# ADDITION & SUBTRACTION
# =========================
print("\nA + B:\n", A + B)
print("A - B:\n", A - B)

# =========================
# ELEMENT-WISE MULTIPLICATION
# =========================
print("\nElement-wise A * B:\n", A * B)

# =========================
# MATRIX MULTIPLICATION
# =========================
print("\nMatrix Multiplication (A @ B):\n", A @ B)
print("Using dot():\n", np.dot(A, B))

# =========================
# TRANSPOSE
# =========================
print("\nTranspose of A:\n", A.T)

# =========================
# DETERMINANT
# =========================
print("\nDeterminant of A:", np.linalg.det(A))

# =========================
# INVERSE
# =========================
print("\nInverse of A:\n", np.linalg.inv(A))

# =========================
# IDENTITY MATRIX
# =========================
I = np.eye(2)
print("\nIdentity Matrix:\n", I)

# =========================
# MATRIX POWER
# =========================
print("\nA squared (A^2):\n", np.linalg.matrix_power(A, 2))

# =========================
# TRACE (sum of diagonal)
# =========================
print("\nTrace of A:", np.trace(A))

# =========================
# EIGEN VALUES & VECTORS
# =========================
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nEigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

# =========================
# RANK
# =========================
print("\nRank of A:", np.linalg.matrix_rank(A))

# =========================
# SOLVE LINEAR EQUATION
# Ax = b
# =========================
b = np.array([5, 11])
x = np.linalg.solve(A, b)
print("\nSolution of Ax = b:\n", x)

# =========================
# STACKING MATRICES
# =========================
print("\nVertical Stack:\n", np.vstack((A, B)))
print("\nHorizontal Stack:\n", np.hstack((A, B)))

# =========================
# RESHAPE
# =========================
C = np.arange(1, 7)
print("\nReshape 1D to 2x3:\n", C.reshape(2,3))

# =========================
# BROADCASTING
# =========================
D = np.array([1, 2])
print("\nBroadcasting A + D:\n", A + D)

# =========================
# MAX, MIN, SUM (AXIS)
# =========================
print("\nColumn-wise sum:\n", np.sum(A, axis=0))
print("Row-wise sum:\n", np.sum(A, axis=1))
print("Max element:", np.max(A))
print("Min element:", np.min(A))

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]

A + B:
 [[ 6  8]
 [10 12]]
A - B:
 [[-4 -4]
 [-4 -4]]

Element-wise A * B:
 [[ 5 12]
 [21 32]]

Matrix Multiplication (A @ B):
 [[19 22]
 [43 50]]
Using dot():
 [[19 22]
 [43 50]]

Transpose of A:
 [[1 3]
 [2 4]]

Determinant of A: -2.0000000000000004

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Identity Matrix:
 [[1. 0.]
 [0. 1.]]

A squared (A^2):
 [[ 7 10]
 [15 22]]

Trace of A: 5

Eigenvalues:
 [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

Rank of A: 2

Solution of Ax = b:
 [1. 2.]

Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]

Reshape 1D to 2x3:
 [[1 2 3]
 [4 5 6]]

Broadcasting A + D:
 [[2 4]
 [4 6]]

Column-wise sum:
 [4 6]
Row-wise sum:
 [3 7]
Max element: 4
Min element: 1
